# Generated by Django 5.0.1 on 2024-05-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteTransferToSts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workforce_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.workforce_workhours')),
            ],
        ),
    ]
