# Generated by Django 5.0.1 on 2024-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_wastetransfertosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastetransfertosts',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
